FROM golang as builder

WORKDIR /app
COPY go.mod .        
COPY main.go .
RUN go build -o server .

FROM gcr.io/distroless/static:nonroot

COPY --from=builder /app/server /
USER nonroot
EXPOSE 8000
CMD ["/server"]
